/**
 * 宿曜占星術 - 二十七宿の定義
 *
 * 宿曜道は密教（金剛界・胎蔵界）に基づく占星術。
 * インドの二十七宿（ナクシャトラ）が中国経由で日本に伝来。
 * 一宿 = 月の公転周期(27.32日) を27等分したもの
 */

export type SukuyoElement = "金" | "日" | "火" | "水" | "木" | "土" | "月";
export type SukuyoNature = "安" | "危" | "中";
export type SukuyoType = "善" | "凶" | "中";

export interface Shuku {
  /** 宿の番号（0〜26） */
  index: number;
  /** 日本語名 */
  name: string;
  /** 読み方 */
  reading: string;
  /** 梵字（サンスクリット名） */
  sanskrit: string;
  /** 守護星（七曜） */
  element: SukuyoElement;
  /** 宿の性質（安全・危険・中間） */
  nature: SukuyoNature;
  /** 吉凶の基本傾向 */
  type: SukuyoType;
  /** 宿の象徴・意味 */
  symbol: string;
  /** 得意なこと */
  strengths: string[];
  /** 注意すること */
  cautions: string[];
  /** 今日のキーワード（運勢文言生成用） */
  keywords: string[];
}

/** 二十七宿の定義（角宿から順番） */
export const SHUKU_LIST: Shuku[] = [
  {
    index: 0,
    name: "角宿",
    reading: "かくしゅく",
    sanskrit: "Citrā",
    element: "金",
    nature: "安",
    type: "善",
    symbol: "龍の角・始まりの宿",
    strengths: ["新規開始", "リーダーシップ", "創造力"],
    cautions: ["独断専行", "焦り"],
    keywords: ["始まり", "創造", "先駆者", "龍", "青春"],
  },
  {
    index: 1,
    name: "亢宿",
    reading: "こうしゅく",
    sanskrit: "Svātī",
    element: "金",
    nature: "危",
    type: "凶",
    symbol: "龍の喉・障壁の宿",
    strengths: ["忍耐力", "慎重さ", "分析力"],
    cautions: ["停滞", "トラブル", "対人摩擦"],
    keywords: ["試練", "忍耐", "慎重", "障壁", "克服"],
  },
  {
    index: 2,
    name: "氐宿",
    reading: "ていしゅく",
    sanskrit: "Viśākhā",
    element: "土",
    nature: "中",
    type: "凶",
    symbol: "龍の胸・選択の宿",
    strengths: ["決断力", "実行力"],
    cautions: ["衝突", "決断の遅れ"],
    keywords: ["選択", "決断", "分岐点", "勇気"],
  },
  {
    index: 3,
    name: "房宿",
    reading: "ぼうしゅく",
    sanskrit: "Anurādhā",
    element: "日",
    nature: "安",
    type: "善",
    symbol: "龍の腹・豊穣の宿",
    strengths: ["人間関係", "協調性", "豊かさ"],
    cautions: ["依存", "流されやすさ"],
    keywords: ["豊穣", "調和", "縁", "友情", "恵み"],
  },
  {
    index: 4,
    name: "心宿",
    reading: "しんしゅく",
    sanskrit: "Jyeṣṭhā",
    element: "月",
    nature: "危",
    type: "凶",
    symbol: "龍の心臓・変革の宿",
    strengths: ["洞察力", "変革力", "深い思考"],
    cautions: ["感情の波", "暗示的な出来事"],
    keywords: ["変革", "洞察", "核心", "月", "内省"],
  },
  {
    index: 5,
    name: "尾宿",
    reading: "びしゅく",
    sanskrit: "Mūla",
    element: "火",
    nature: "安",
    type: "善",
    symbol: "龍の尾・根源の宿",
    strengths: ["根性", "継続力", "家族縁"],
    cautions: ["執着", "過去への囚われ"],
    keywords: ["根源", "継続", "家族", "大地", "粘り強さ"],
  },
  {
    index: 6,
    name: "箕宿",
    reading: "きしゅく",
    sanskrit: "Pūrvāṣāḍhā",
    element: "水",
    nature: "中",
    type: "善",
    symbol: "みの・風の宿",
    strengths: ["柔軟性", "適応力", "コミュニケーション"],
    cautions: ["落ち着きのなさ", "散漫"],
    keywords: ["風", "変化", "適応", "流れ", "自由"],
  },
  {
    index: 7,
    name: "斗宿",
    reading: "としゅく",
    sanskrit: "Uttarāṣāḍhā",
    element: "金",
    nature: "安",
    type: "善",
    symbol: "北斗七星・勝利の宿",
    strengths: ["目標達成", "勝負強さ", "出世"],
    cautions: ["高慢", "周囲との摩擦"],
    keywords: ["勝利", "目標", "達成", "名誉", "星"],
  },
  {
    index: 8,
    name: "牛宿",
    reading: "ごしゅく",
    sanskrit: "Śravaṇa",
    element: "金",
    nature: "危",
    type: "凶",
    symbol: "牛・奉仕の宿",
    strengths: ["誠実さ", "勤勉", "奉仕精神"],
    cautions: ["苦労", "損失", "過労"],
    keywords: ["誠実", "奉仕", "忍耐", "努力", "牛"],
  },
  {
    index: 9,
    name: "女宿",
    reading: "じょしゅく",
    sanskrit: "Dhaniṣṭhā",
    element: "土",
    nature: "中",
    type: "中",
    symbol: "女性・技芸の宿",
    strengths: ["芸術性", "技術", "感性"],
    cautions: ["感情的になりやすい", "自己犠牲"],
    keywords: ["芸術", "感性", "技巧", "女性", "美"],
  },
  {
    index: 10,
    name: "虚宿",
    reading: "きょしゅく",
    sanskrit: "Śatabhiṣā",
    element: "日",
    nature: "危",
    type: "凶",
    symbol: "空虚・再生の宿",
    strengths: ["再生力", "神秘的洞察", "瞑想"],
    cautions: ["孤独感", "喪失", "不安定"],
    keywords: ["再生", "空", "神秘", "瞑想", "静寂"],
  },
  {
    index: 11,
    name: "危宿",
    reading: "きしゅく",
    sanskrit: "Pūrvābhādrapadā",
    element: "月",
    nature: "危",
    type: "凶",
    symbol: "危険・高みの宿",
    strengths: ["高い理想", "精神力"],
    cautions: ["危険", "高所からの転落", "油断禁物"],
    keywords: ["警戒", "慎重", "高み", "試練", "覚悟"],
  },
  {
    index: 12,
    name: "室宿",
    reading: "しつしゅく",
    sanskrit: "Uttarābhādrapadā",
    element: "火",
    nature: "安",
    type: "善",
    symbol: "家・安住の宿",
    strengths: ["家庭運", "安定", "建設"],
    cautions: ["保守的すぎる", "変化への抵抗"],
    keywords: ["安住", "家庭", "安定", "建設", "基盤"],
  },
  {
    index: 13,
    name: "壁宿",
    reading: "へきしゅく",
    sanskrit: "Revatī",
    element: "水",
    nature: "安",
    type: "善",
    symbol: "城壁・守護の宿",
    strengths: ["守護力", "完成", "旅行運"],
    cautions: ["頑固", "閉鎖的"],
    keywords: ["守護", "完成", "旅", "壁", "境界"],
  },
  {
    index: 14,
    name: "奎宿",
    reading: "けいしゅく",
    sanskrit: "Aśvinī",
    element: "木",
    nature: "安",
    type: "善",
    symbol: "豚・文芸の宿",
    strengths: ["学問", "文芸", "創造"],
    cautions: ["優柔不断", "批判的すぎる"],
    keywords: ["文芸", "学問", "創造", "知性", "始動"],
  },
  {
    index: 15,
    name: "婁宿",
    reading: "ろうしゅく",
    sanskrit: "Bharaṇī",
    element: "金",
    nature: "安",
    type: "善",
    symbol: "犬・集合の宿",
    strengths: ["人を集める", "交渉力", "財運"],
    cautions: ["欲張り", "散財"],
    keywords: ["集合", "縁結び", "財", "交渉", "豊か"],
  },
  {
    index: 16,
    name: "胃宿",
    reading: "いしゅく",
    sanskrit: "Kṛttikā",
    element: "土",
    nature: "中",
    type: "善",
    symbol: "蓄える・保管の宿",
    strengths: ["蓄積", "保管", "堅実さ"],
    cautions: ["ケチ", "頑固"],
    keywords: ["蓄積", "保管", "堅実", "土台", "安全"],
  },
  {
    index: 17,
    name: "昴宿",
    reading: "ぼうしゅく",
    sanskrit: "Rohiṇī",
    element: "日",
    nature: "危",
    type: "中",
    symbol: "プレアデス・集まりの宿",
    strengths: ["集中力", "精密さ", "繊細さ"],
    cautions: ["感情的", "孤立"],
    keywords: ["集中", "精密", "星団", "繊細", "深化"],
  },
  {
    index: 18,
    name: "畢宿",
    reading: "ひつしゅく",
    sanskrit: "Mṛgaśīrṣa",
    element: "月",
    nature: "中",
    type: "善",
    symbol: "網・捕獲の宿",
    strengths: ["交渉力", "実行力", "捕獲"],
    cautions: ["強引さ", "トラブル"],
    keywords: ["実行", "捕獲", "交渉", "行動力", "成果"],
  },
  {
    index: 19,
    name: "觜宿",
    reading: "ししゅく",
    sanskrit: "Ārdrā",
    element: "火",
    nature: "危",
    type: "凶",
    symbol: "くちばし・饒舌の宿",
    strengths: ["言語力", "説得力"],
    cautions: ["口争い", "言い過ぎ", "誤解"],
    keywords: ["言葉", "説得", "表現", "コミュニケーション", "声"],
  },
  {
    index: 20,
    name: "参宿",
    reading: "さんしゅく",
    sanskrit: "Punarvasū",
    element: "水",
    nature: "安",
    type: "善",
    symbol: "オリオン・白虎の宿",
    strengths: ["勇気", "勝負", "突破力"],
    cautions: ["向こう見ず", "けんか"],
    keywords: ["勇気", "突破", "勝負", "白虎", "前進"],
  },
  {
    index: 21,
    name: "井宿",
    reading: "せいしゅく",
    sanskrit: "Puṣya",
    element: "木",
    nature: "安",
    type: "善",
    symbol: "井戸・恵みの宿",
    strengths: ["財運", "恵み", "人望"],
    cautions: ["慢心", "浪費"],
    keywords: ["恵み", "財運", "人望", "井戸", "豊穣"],
  },
  {
    index: 22,
    name: "鬼宿",
    reading: "きしゅく",
    sanskrit: "Āśleṣā",
    element: "金",
    nature: "危",
    type: "凶",
    symbol: "鬼・霊験の宿",
    strengths: ["霊感", "洞察力", "変化への対応"],
    cautions: ["怨念", "因縁", "不吉な兆候"],
    keywords: ["霊験", "変化", "洞察", "因縁", "転換"],
  },
  {
    index: 23,
    name: "柳宿",
    reading: "りゅうしゅく",
    sanskrit: "Maghā",
    element: "土",
    nature: "危",
    type: "凶",
    symbol: "柳・悲哀の宿",
    strengths: ["感受性", "芸術性"],
    cautions: ["悲観", "病気", "損失"],
    keywords: ["感受性", "悲哀", "柳", "雨", "流れ"],
  },
  {
    index: 24,
    name: "星宿",
    reading: "せいしゅく",
    sanskrit: "Pūrvaphalgunī",
    element: "日",
    nature: "危",
    type: "凶",
    symbol: "星・孤高の宿",
    strengths: ["個性", "独立心", "輝き"],
    cautions: ["孤立", "傲慢", "批判"],
    keywords: ["輝き", "孤高", "個性", "星", "独立"],
  },
  {
    index: 25,
    name: "張宿",
    reading: "ちょうしゅく",
    sanskrit: "Uttaraphalgunī",
    element: "月",
    nature: "安",
    type: "善",
    symbol: "弓・拡大の宿",
    strengths: ["拡大", "繁栄", "実力発揮"],
    cautions: ["過信", "拡張しすぎ"],
    keywords: ["拡大", "繁栄", "飛躍", "弓", "発展"],
  },
  {
    index: 26,
    name: "翼宿",
    reading: "よくしゅく",
    sanskrit: "Hasta",
    element: "火",
    nature: "危",
    type: "凶",
    symbol: "翼・旅の宿",
    strengths: ["行動力", "冒険心", "旅運"],
    cautions: ["疲弊", "消耗", "遠出でのトラブル"],
    keywords: ["翼", "旅", "冒険", "飛翔", "変遷"],
  },
];

/** 宿の名前でインデックスを引くマップ */
export const SHUKU_BY_NAME = Object.fromEntries(
  SHUKU_LIST.map((s) => [s.name, s])
);

/** 二十七宿のサイクル（インデックス順） */
export const SHUKU_COUNT = 27;
